load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "config",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "@crates//:anyhow",
        "@crates//:serde",
        "@crates//:serde-saphyr",
    ],
)

rust_test(
    name = "config_test",
    size = "small",
    crate = ":config",
)
